debug terraform plan

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -41,18 +41,33 @@ jobs:
         id: plan
         continue-on-error: true
         run: |
-          terraform plan -detailed-exitcode
+          terraform plan -detailed-exitcode || true
           EXIT_CODE=$?
+
           if [ $EXIT_CODE -eq 2 ]; then
-            exit 0
-          elif [ $EXIT_CODE -ne 0 ]; then
-            exit $EXIT_CODE
+            echo "Terraform detected changes."
+            echo "::set-output name=terraform_exit_code::2"
+          elif [ $EXIT_CODE -eq 1 ]; then
+            echo "Terraform encountered an error."
+            echo "::set-output name=terraform_exit_code::1"
+          else
+            echo "No changes detected."
+            echo "::set-output name=terraform_exit_code::0"
           fi
+
+      - name: Conditional Actions Based on Terraform Plan
+        if: steps.terraform-plan.outputs.terraform_exit_code == '1'
+        run: echo "Terraform failed with an error!"
+        continue-on-error: false
+
+      - name: Proceed if Changes Were Detected
+        if: steps.terraform-plan.outputs.terraform_exit_code == '2'
+        run: echo "Proceeding with changes detected by Terraform."
 
   terraform_apply:
     runs-on: ubuntu-latest
     needs: terraform_plan
-    if: success() && needs.terraform_plan.outputs.exitcode == '2'
+    if: success() && needs.terraform_plan.outputs.terraform_exit_code == '2'
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
